baseURL       = "https://ilhamzz.netlify.app"
languageCode  = "en-us"
title         = "Ilhamzz | Rajanya Custom Keyboard"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Tentang"
    url     = "tentang"
    weight  = 2
  [[menu.nav]]
    name    = "Produk"
    url     = "produk"
    weight  = 3
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/sakura1.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Ilhamzz | Custom Keyboard"
  author = "Ilham"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  # formspreeFormUrl  = "https://formspree.io/myykjpje"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Pilihan"
    placeholder_about_the_project = "Ada request? Masukkan disini "
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Custom Keyboard 1"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Custom Keyboard 2"
      [[params.contactForm.projectType]]
      value = "gd"
      title  = "Custom Keyboard 3"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Custom Keyboard 4"
      [[params.contactForm.projectType]]
      value = "gd"
      title  = "Custom Keyboard 5"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Custom Keycaps"
      
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/background.jpg"
    heading               = "Rajanya custom keyboard harga minimalis"
    tagline               = "Bingung mau model apa? Datang ke kami aja"
    primary_button        = "Lihat Keyboard"
    primary_button_url    = "produk"
    secondary_button      = "Hubungi Kami"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Daftar Keyboard"
    subtitle  = "Kami memastikan bahwa custom keyboard yang kami jual adalah barang original, berkualitas dan Aesthetic."

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Kontak Kami"
      address = "Pangkalpinang,<br>Jalan Koba"
      phone   = "0821-0821-0821"
      email   = "info@ilhamzz.app"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Tentang Kami"
          url  = "tentang"
        [[params.footer.sitemap.link]]
          name = "Lihat Produk"
          url  = "produk"
        [[params.footer.sitemap.link]]
          name = "Hubungi Kami"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Kesenangan dan kepercayaan dari pelanggan adalah Prioritas kami."
